// Generated by CoffeeScript 1.9.2
Polymer({
  is: "burn-chart",
  properties: {
    step: {
      type: Number,
      observer: "gotoStep"
    }
  },
  created: function() {
    var rect, svg;
    svg = window.yako.svg;
    this.root = svg.create('svg').attr({
      id: 'burn-chart',
      xmlns: "http://www.w3.org/2000/svg",
      width: '100%',
      height: '100%',
      'xmlns:xlink': "http://www.w3.org/1999/xlink"
    });
    rect = '<rect id="SvgjsRect1006" width="100%" height="100%" x="0" y="0" fill="none" stroke="#000000" stroke-width="1"></rect>';
    return this.root.append(rect);
  },
  setAttribute: function(attr, value) {
    return this.innerHTML = "The value of attribute " + attr + " is " + value;
  },
  gotoStep: function(step) {
    return this.innerHTML = this.root.stringify();
  }
});
