// Generated by CoffeeScript 1.9.2
Polymer({
  is: "burn-demo",
  ready: function() {
    this.gestureActive = true;
    this.step = 0;
    return this.steps = [
      {
        index: 0
      }, {
        index: 1
      }, {
        index: 2
      }
    ];
  },
  properties: {
    step: Number
  },
  _listTap: function() {
    return this.$.drawerPanel.closeDrawer();
  },
  forward: function() {
    if (this.step < this.steps.length - 1 && this.gestureActive) {
      this.gestureActive = false;
      this.step++;
      return setTimeout(this.enableGesture, 200);
    }
  },
  back: function() {
    if (this.step > 0 && this.gestureActive) {
      this.gestureActive = false;
      this.step--;
      return setTimeout(this.enableGesture, 200);
    }
  },
  enableGesture: function() {
    return document.querySelector('burn-demo').gestureActive = true;
  }
});
