// Generated by CoffeeScript 1.9.2
Polymer({
  is: "x-app",
  ready: function() {
    this.step = 0;
    return this.steps = [
      {
        index: 0
      }, {
        index: 1
      }, {
        index: 2
      }
    ];
  },
  properties: {
    _isMobile: {
      type: Boolean,
      observer: "_isMobileChanged"
    },
    step: Number
  },
  _listTap: function() {
    return this.$.drawerPanel.closeDrawer();
  },
  _isMobileChanged: function(isMobile) {
    this.mainMode = (isMobile ? "seamed" : "cover");
    this.drawerWidth = (isMobile ? "100%" : "50px");
    this.toolbarClass = (isMobile ? "" : "tall");
    return this.updateStyles();
  },
  forward: function() {
    if (!(this.step >= this.steps.length - 1)) {
      return this.step++;
    }
  },
  back: function() {
    if (this.step !== 0) {
      return this.step--;
    }
  }
});
