// Generated by CoffeeScript 1.9.2
Polymer({
  is: "x-app",
  ready: function() {
    console.log('ready');
    return this.steps = [
      {
        index: 0
      }, {
        index: 1
      }, {
        index: 2
      }
    ];
  },
  properties: {
    _isMobile: {
      type: Boolean,
      observer: "_isMobileChanged"
    }
  },
  _listTap: function() {
    console.log('clicked');
    return this.$.drawerPanel.closeDrawer();
  },
  _isMobileChanged: function(isMobile) {
    this.mainMode = (isMobile ? "seamed" : "cover");
    this.drawerWidth = (isMobile ? "100%" : "50px");
    this.toolbarClass = (isMobile ? "" : "tall");
    return this.updateStyles();
  }
});
